from pathlib import Path
import unittest


class WorkflowScheduleTests(unittest.TestCase):
    def test_hourly_refresh_also_recovers_daily_email(self):
        workflow = (Path(__file__).parents[1] / ".github/workflows/analyze-and-deploy.yml").read_text(encoding="utf-8")
        self.assertIn('cron: "17 * * * *"', workflow)
        self.assertNotIn('cron: "17 0-21,23 * * *"', workflow)
        self.assertNotIn('cron: "20 22 * * *"', workflow)
        self.assertNotIn('cron: "30 22 * * *"', workflow)
        self.assertEqual(workflow.count('NOT_BEFORE_KST: "07:00"'), 2)
        self.assertIn("steps.coin_delivery.outputs.should_send == 'true'", workflow)
        self.assertIn("steps.stock_delivery.outputs.should_send == 'true'", workflow)
        self.assertIn("[record-daily-email]", workflow)
        self.assertIn("FORCE_SEND: ${{ github.event_name == 'push' }}", workflow)
        self.assertIn("actions/upload-artifact@v4", workflow)
        self.assertIn("github.event_name == 'workflow_dispatch' && inputs.send_email", workflow)
        self.assertIn("default: false", workflow)
        self.assertIn("[send-test-email]", workflow)
        self.assertIn("[send-stock-test-email]", workflow)
        self.assertIn("EMAIL_REPORT_SCOPE:", workflow)
        self.assertIn("[send-daily-email]", workflow)
        self.assertIn("STOCK_EMAIL_TO: ${{ secrets.STOCK_EMAIL_TO }}", workflow)
        self.assertIn("STOCK_HOLDINGS_US: ${{ secrets.STOCK_HOLDINGS_US }}", workflow)
        self.assertIn("STOCK_HOLDINGS_KR: ${{ secrets.STOCK_HOLDINGS_KR }}", workflow)
        self.assertIn("STOCK_SECTORS: ${{ secrets.STOCK_SECTORS }}", workflow)
        self.assertIn("SUPABASE_URL: ${{ secrets.SUPABASE_URL }}", workflow)
        self.assertIn("SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}", workflow)
        self.assertIn("SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}", workflow)
        self.assertIn("SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}", workflow)
        self.assertIn("KIS_SCHEDULER_KEY: ${{ secrets.KIS_SCHEDULER_KEY }}", workflow)
        self.assertIn('REQUIRE_MEMBER_STOCK_PROFILE: "true"', workflow)
        self.assertIn("load_member_stock_profile.py", workflow)
        self.assertIn('REQUIRE_MEMBER_STOCK_PROFILE: "true"', workflow)
        self.assertIn("python scripts/write_supabase_config.py", workflow)
        self.assertIn("id: coin_delivery", workflow)
        self.assertIn("id: stock_delivery", workflow)
        self.assertIn("id: kis_profile", workflow)
        self.assertIn("continue-on-error:", workflow)
        self.assertIn("DELIVERY_MARKER_SCOPE: coin", workflow)
        self.assertIn("DELIVERY_MARKER_SCOPE: stock", workflow)
        self.assertIn("steps.kis_profile.outcome == 'success'", workflow)
        self.assertIn("[deploy-supabase-only]", workflow)

    def test_daily_email_has_fallback_and_never_cancels_delivery(self):
        workflow = (Path(__file__).parents[1] / ".github/workflows/daily-email.yml").read_text(encoding="utf-8")
        self.assertNotIn('cron: "20 22 * * *"', workflow)
        self.assertIn('cron: "50 22 * * *"', workflow)
        self.assertIn("cancel-in-progress: false", workflow)
        self.assertIn("check_daily_email_delivery.py", workflow)
        self.assertIn("validate_email_config.py", workflow)
        self.assertIn("REQUIRE_EMAIL_DELIVERY: \"true\"", workflow)
        self.assertIn("actions/upload-artifact@v4", workflow)
        self.assertIn("load_member_stock_profile.py", workflow)
        self.assertIn("id: coin_delivery", workflow)
        self.assertIn("id: stock_delivery", workflow)
        self.assertIn("continue-on-error: true", workflow)
        self.assertIn("EMAIL_REPORT_SCOPE:", workflow)

    def test_supabase_backend_deploy_targets_owned_project(self):
        workflow = (Path(__file__).parents[1] / ".github/workflows/deploy-supabase.yml").read_text(encoding="utf-8")
        self.assertIn("pgtxtnggjqaysjhtdepz", workflow)
        self.assertIn("SUPABASE_ACCESS_TOKEN", workflow)
        self.assertIn("SUPABASE_DB_PASSWORD", workflow)
        self.assertIn('branches: [main]', workflow)
        self.assertIn('"supabase/**"', workflow)
        self.assertIn("supabase db push --linked", workflow)
        self.assertIn("functions deploy kis-portfolio", workflow)
        self.assertIn("--no-verify-jwt", workflow)
        self.assertIn("KIS_OWNER_EMAIL_CANDIDATE", workflow)
        self.assertIn('supabase secrets set KIS_OWNER_EMAIL=', workflow)
        self.assertIn("[resend-auth-email]", workflow)
        self.assertIn("resend_owner_confirmation.py", workflow)


if __name__ == "__main__":
    unittest.main()
