create table if not exists public.asset_portfolio_daily_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  snapshot_date date not null,
  positions jsonb not null default '[]'::jsonb,
  totals jsonb not null default '{}'::jsonb,
  fx_rate numeric,
  fx_date date,
  fx_source text,
  complete boolean not null default true,
  warnings jsonb not null default '[]'::jsonb,
  captured_at timestamptz not null default now(),
  unique (user_id, snapshot_date)
);
create index if not exists asset_portfolio_daily_user_date_idx on public.asset_portfolio_daily_snapshots(user_id, snapshot_date desc);
alter table public.asset_portfolio_daily_snapshots enable row level security;
create policy "members read own daily asset snapshots" on public.asset_portfolio_daily_snapshots for select to authenticated using ((select auth.uid()) = user_id);
revoke all on table public.asset_portfolio_daily_snapshots from anon;
grant select on table public.asset_portfolio_daily_snapshots to authenticated;
