alter table if exists public.user_preferences
  add column if not exists holdings_us text not null default '',
  add column if not exists holdings_kr text not null default '',
  add column if not exists sector_ids text[] not null default '{}',
  add column if not exists coin_email text,
  add column if not exists stock_email text,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.user_preferences enable row level security;

drop policy if exists "members can read own preferences" on public.user_preferences;
create policy "members can read own preferences"
on public.user_preferences for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "members can create own preferences" on public.user_preferences;
create policy "members can create own preferences"
on public.user_preferences for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "members can update own preferences" on public.user_preferences;
create policy "members can update own preferences"
on public.user_preferences for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on table public.user_preferences from anon;
grant select, insert, update on table public.user_preferences to authenticated;

create table if not exists public.kis_portfolio_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  positions jsonb not null default '[]'::jsonb,
  totals jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now()
);

create index if not exists kis_portfolio_snapshots_user_captured_idx
on public.kis_portfolio_snapshots (user_id, captured_at desc);

alter table public.kis_portfolio_snapshots enable row level security;

drop policy if exists "members can read own portfolio snapshots" on public.kis_portfolio_snapshots;
create policy "members can read own portfolio snapshots"
on public.kis_portfolio_snapshots for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "members can create own portfolio snapshots" on public.kis_portfolio_snapshots;
create policy "members can create own portfolio snapshots"
on public.kis_portfolio_snapshots for insert to authenticated
with check ((select auth.uid()) = user_id);

revoke all on table public.kis_portfolio_snapshots from anon;
grant select, insert on table public.kis_portfolio_snapshots to authenticated;

