create table if not exists public.kis_portfolio_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  positions jsonb not null default '[]'::jsonb,
  totals jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now()
);

create index if not exists kis_portfolio_snapshots_user_captured_idx
on public.kis_portfolio_snapshots (user_id, captured_at desc);

alter table public.kis_portfolio_snapshots enable row level security;

drop policy if exists "members can read own portfolio snapshots" on public.kis_portfolio_snapshots;
create policy "members can read own portfolio snapshots"
on public.kis_portfolio_snapshots for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "members can create own portfolio snapshots" on public.kis_portfolio_snapshots;
create policy "members can create own portfolio snapshots"
on public.kis_portfolio_snapshots for insert to authenticated
with check ((select auth.uid()) = user_id);

revoke all on table public.kis_portfolio_snapshots from anon;
grant select, insert on table public.kis_portfolio_snapshots to authenticated;
